apiVersion: 1

datasources:
  - name: prometheusdata
    type: prometheus
    access: proxy
    orgId: 1
    url: http://<external-ip/service-name>:9090 #external ip - if deployed locally
    basicAuth: false
    isDefault: true
    editable: true